version: '3.8'

volumes:
  postgres_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:13.0-alpine
    container_name: wardrobe_wonderland_db
    env_file: Wardrobe_Wonderland/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  wardrobe_wonderland:
    build: ./Wardrobe_Wonderland
    container_name: wardrobe_wonderland-wardrobe_wonderland
    env_file: Wardrobe_Wonderland/.env
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    depends_on:
      - db
    ports:
      - 8000:8000
    links:
      - db
    restart: always
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py collectstatic --noinput &&
                    gunicorn Wardrobe_Wonderland.wsgi:application --bind 0.0.0.0:8000 &&
                    stripe listen --forward-to localhost:8000/payment/webhook_stripe/"

  redis:
    image: redis:7.2.3-alpine
    container_name: wardrobe_wonderland_redis
    restart: unless-stopped

  celery:
    build: ./Wardrobe_Wonderland
    container_name: wardrobe_wonderland_celery
    env_file: Wardrobe_Wonderland/.env
    depends_on:
      - db
      - redis
    volumes:
      - static_data:/app/static
    restart: always
    command: celery -A Wardrobe_Wonderland worker --loglevel=info --beat

  nginx:
    image: nginx:latest
    container_name: wardrobe_wonderland_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - 80:80
    restart: always