# Generated by Django 4.2.6 on 2024-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_userorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
