# Generated by Django 4.2.6 on 2024-06-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_orderitem_brand_userorder_brand_userorder_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
        ),
    ]
