# Generated by Django 4.2.6 on 2024-06-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='type',
        ),
    ]
