# Generated by Django 4.2.6 on 2024-06-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0003_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory',
            field=models.CharField(max_length=40),
        ),
    ]
