# Generated by Django 4.2.6 on 2024-06-23 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0005_size_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item_manager.subcategory'),
        ),
    ]
