# Generated by Django 4.2.6 on 2024-06-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0006_brand_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=40),
        ),
    ]
