# Generated by Django 4.2.6 on 2024-06-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0007_alter_brand_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='brand',
            name='subcategory',
            field=models.ManyToManyField(to='item_manager.subcategory'),
        ),
    ]
