# Generated by Django 4.2.6 on 2024-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0009_remove_brand_subcategory_brand_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='size',
            name='subcategory',
            field=models.ManyToManyField(default=1, to='item_manager.subcategory'),
        ),
    ]
