# Generated by Django 4.2.6 on 2024-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0011_remove_size_subcategory_size_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='size',
            name='subcategory',
            field=models.ManyToManyField(to='item_manager.subcategory'),
        ),
    ]
