# Generated by Django 4.2.6 on 2024-06-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0013_remove_subcategory_category_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='category',
            field=models.ManyToManyField(to='item_manager.category'),
        ),
    ]
