# Generated by Django 4.2.6 on 2024-06-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0014_type_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='brand',
            name='subcategory',
            field=models.ManyToManyField(to='item_manager.subcategory'),
        ),
    ]
