# Generated by Django 4.2.6 on 2024-06-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0009_remove_brand_subcategory_brand_subcategory'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ManyToManyField(default=1, related_name='colors', to='item_manager.color'),
        ),
    ]
