# Generated by Django 4.2.7 on 2024-01-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='men_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_sub_categories', to='shop.mensubcategory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='women_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='women_sub_categories', to='shop.womensubcategory'),
        ),
    ]
