# Generated by Django 4.2.7 on 2024-01-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_size_dresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='color',
            new_name='accessories_color',
        ),
        migrations.AddField(
            model_name='item',
            name='clothing_color',
            field=models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('PURPLE', 'Purple'), ('PINK', 'Pink'), ('ORANGE', 'Orange'), ('BROWN', 'Brown'), ('GRAY', 'Gray'), ('NAVY', 'Navy'), ('TURQUOISE', 'Turquoise'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='BLACK', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='dresses_color',
            field=models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('PURPLE', 'Purple'), ('PINK', 'Pink'), ('ORANGE', 'Orange'), ('BROWN', 'Brown'), ('GRAY', 'Gray'), ('NAVY', 'Navy'), ('TURQUOISE', 'Turquoise'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='BLACK', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='shoes_color',
            field=models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('PURPLE', 'Purple'), ('PINK', 'Pink'), ('ORANGE', 'Orange'), ('BROWN', 'Brown'), ('GRAY', 'Gray'), ('NAVY', 'Navy'), ('TURQUOISE', 'Turquoise'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='BLACK', max_length=20),
        ),
    ]
