# Generated by Django 4.2.7 on 2024-01-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_item_accessories_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='accessories_color',
            field=models.CharField(blank=True, choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('PURPLE', 'Purple'), ('PINK', 'Pink'), ('ORANGE', 'Orange'), ('BROWN', 'Brown'), ('GRAY', 'Gray'), ('NAVY', 'Navy'), ('TURQUOISE', 'Turquoise'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='clothing_color',
            field=models.CharField(blank=True, choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('PURPLE', 'Purple'), ('PINK', 'Pink'), ('ORANGE', 'Orange'), ('BROWN', 'Brown'), ('GRAY', 'Gray'), ('NAVY', 'Navy'), ('TURQUOISE', 'Turquoise'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='dresses_color',
            field=models.CharField(blank=True, choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('PURPLE', 'Purple'), ('PINK', 'Pink'), ('ORANGE', 'Orange'), ('BROWN', 'Brown'), ('GRAY', 'Gray'), ('NAVY', 'Navy'), ('TURQUOISE', 'Turquoise'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='shoes_color',
            field=models.CharField(blank=True, choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('PURPLE', 'Purple'), ('PINK', 'Pink'), ('ORANGE', 'Orange'), ('BROWN', 'Brown'), ('GRAY', 'Gray'), ('NAVY', 'Navy'), ('TURQUOISE', 'Turquoise'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], max_length=20, null=True),
        ),
    ]
