# Generated by Django 4.2.6 on 2024-04-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_item_accessories_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.item',),
        ),
    ]
