# Generated by Django 4.2.6 on 2024-06-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_item_size_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
