# Generated by Django 4.2.7 on 2023-12-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='shop.item'),
        ),
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
