# Generated by Django 4.2.7 on 2023-12-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_user_favorites_delete_userpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
    ]
